- name: sudo bridge test
  hosts: pwrcntr
  gather_facts: false
 
  tasks:
  - name: create directory
    ansible.builtin.file:
      path: "/tmp/test_dvo"
      state: directory
      mode: u+rwx,g+rx-w,o-rwx
    become: true
    become_user: diederickdebuck
    become_method: sudo